### ISSUE TITLE
Remove Cisco logo

### ISSUE THREAD

**Issue by nicholaides** [promptworks/ciscospark-survey-bot#47]
- [x] header
- [x] ~login page~

**Comment by nicholaides** [comment]
@jfield44:

question 1. We can we leave the logo that's inside the login-via-OAuth button, right?

<img width="875" alt="screen shot 2017-09-14 at 6 27 11 pm" src="https://user-images.githubusercontent.com/9061/30458696-abeb6df8-997a-11e7-9671-3aead0eb361d.png">

question 2. For the logo in the header, can we say "Survey Bot for Cisco Spark" and have the "Cisco Spark" be slightly stylized?

**Comment by jfield44** [comment]
Sure
