### ISSUE TITLE
Missing intro when surveying

### ISSUE THREAD

**Issue by nicholaides** [promptworks/ciscospark-survey-bot#51]
Should have the title, description, and a welcome message.

<img width="1320" alt="screen shot 2017-09-20 at 10 47 00" src="https://user-images.githubusercontent.com/9061/30667058-4ca940d2-9e24-11e7-9c60-1aa01adb6cc5.png">

**Comment by nicholaides** [comment]
@jfield44 So, I think it comes down to [this line](https://github.com/promptworks/ciscospark-survey-bot/blob/master/src/handlers/conductSurvey.js#L26). Looks like BotKit dropped the message, (which isn't unheard of, actually)

Does this happen consistently or is it intermittent? You could duplicate survey and try it on a different room to test it out.

**Comment by jfield44** [comment]
Will duplicate again to test. If its a 429 or an error from Botkit then I see two options, 1 is a quick fix and just to hit our API directly handling the 429 if there is throttling, or ill see if I can get Ben to patch it on the Botkit side but not sure how long that would take.

Given that I've only used it a couple of times and it affected me we need to figure out a fix, will revert back shortly.
