### ISSUE TITLE
Prevent Survey from being sent without a recipient

### ISSUE THREAD

**Issue by jfield44** [promptworks/ciscospark-survey-bot#57]
There is no check today to see if there is a valid recipient or spark room selected. We need some basic checking to see if there is a recipient or not and block the Survey from being sent without it.

**Comment by nicholaides** [comment]
@jfield44 I have some questions. Below which I propose my own answers. Does this match what you are thinking?

Q: What makes a recipient invalid?
A:
- user email is not in the whitelist of email domains (assuming one is provided)
- user is not a bot (@sparkbot.io)

Q: What makes an space invalid?
A: it contains no users that are valid

**Comment by nicholaides** [comment]
Here's the/a problem:

![](https://d26dzxoao6i3hh.cloudfront.net/items/0x1O3h2z3I471X230y2z/Screen%20Recording%202017-11-16%20at%2012.12%20PM.gif)

**Comment by nicholaides** [comment]
Here's the other part of the bug:
![](https://d26dzxoao6i3hh.cloudfront.net/items/3L1f2Y372f062S2D1p0d/Screen%20Recording%202017-12-04%20at%2011.58%20AM.gif)
